language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    #    - libgtest-dev
    - cmake

before_script:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script:
- cmake .
- cmake --build .
#- cmake --build . --target test
- cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u artbataev:$BINTRAY_API_KEY "https://api.bintray.com/content/artbataev1/Otus_Assignments/Otus_Cpp_2/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;publish=1"
  on:
    branch: master
